name: Rohit Bandaru
description: Deep Learning Researcher
avatar: https://raw.githubusercontent.com/rohitbandaru/blog/master/images/rohit.jpg

footer-links:
  email:  roh.bandaru@gmail.com
  github: RohitBandaru
  linkedin: Rohit-Bandaru
  twitter: rohit_bandaru

google_analytics: UA-204393187-1

url:  RohitBandaru.github.io
baseurl: "/blog"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
